Mercado/Controllers/AdministrationController.cs
using Mercado.Data.Identity;
using Mercado.Models.Account;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Mercado.Controllers
{
    public class AdministrationController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<UserCustom> _userManager;

        public AdministrationController(RoleManager<IdentityRole> roleManager,
            UserManager<UserCustom> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        [HttpGet]
        public IActionResult ListRole()
        {
            var roles = _roleManager.Roles;

            return View(roles);
        }

        [HttpGet]
        public IActionResult CreateRole()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateRole(CreateRoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                IdentityRole identityRole = new IdentityRole
                {
                    Name = model.RoleName
                };

                IdentityResult result = await _roleManager.CreateAsync(identityRole);

                if (result.Succeeded)
                {
                    return RedirectToAction("ListRole");
                }

                foreach (IdentityError error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }

            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> EditRole(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Função não encontrada";
                return View("NotFound");
            }

            var model = new EditRoleViewModel
            {
                Id = role.Id,
                RoleName = role.Name
            };

            foreach (var user in _userManager.Users)
            {
                if (await _userManager.IsInRoleAsync(user, role.Name))
                {
                    model.Users.Add(user.UserName);
                }
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditRole(EditRoleViewModel model)
        {
            var role = await _roleManager.FindByIdAsync(model.Id);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {model.Id} cannot be found";
                return View("NotFound");
            }
            else
            {
                role.Name = model.RoleName;

                var result = await _roleManager.UpdateAsync(role);

                if (result.Succeeded)
                {
                    return RedirectToAction("ListRole");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

                return View(model);
            }
        }
        [HttpGet]
        public async Task<IActionResult> EditUsersInRole(string roleId)
        {
            ViewBag.roleId = roleId;

            var role = await _roleManager.FindByIdAsync(roleId);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Função não encontrada";
                return View();
            }

            var model = new List<UserRoleViewModel>();

            foreach (var user in _userManager.Users)
            {
                var userRoleViewModel = new UserRoleViewModel
                {
                    UserId = user.Id,
                    UserName = user.UserName
                };

                if (await _userManager.IsInRoleAsync(user, role.Name))
                {
                    userRoleViewModel.IsSelected = true;
                }
                else
                {
                    userRoleViewModel.IsSelected = false;
                }

                model.Add(userRoleViewModel);
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditUsersInRole(List<UserRoleViewModel> model, string roleId)
        {
            var role = await _roleManager.FindByIdAsync(roleId);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Função não encontrada";
                return View();
            }

            for (int i = 0; i < model.Count; i++)
            {
                var user = await _userManager.FindByIdAsync(model[i].UserId);

                IdentityResult result = null;

                if (model[i].IsSelected && !(await _userManager.IsInRoleAsync(user, role.Name)))
                {
                    result = await _userManager.AddToRoleAsync(user, role.Name);
                }
                else if (!model[i].IsSelected && await _userManager.IsInRoleAsync(user, role.Name))
                {
                    result = await _userManager.RemoveFromRoleAsync(user, role.Name);
                }
                else
                {
                    continue;
                }

                if (result.Succeeded)
                {
                    if (i < (model.Count - 1))
                        continue;
                    else
                        return RedirectToAction("EditRole", new { Id = roleId });
                }
            }

            return RedirectToAction("EditRole", new { Id = roleId });
        }

        [HttpGet]
        public async Task<IActionResult> DeleteRole(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _roleManager.FindByIdAsync(id);

            if (role == null)
            {
                return NotFound();
            }
            return View(role);
        }

        [HttpPost, ActionName("DeleteRole")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteRoleConfirmed(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Função não encontrada";
                return View("NotFound");
            }
            else
            {
                var result = await _roleManager.DeleteAsync(role);

                if (result.Succeeded)
                {
                    return RedirectToAction("ListRole");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

                return View("ListRole");
            }
        }
    }
}

Mercado/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Mercado.Data;
using Mercado.Models;
using Microsoft.AspNetCore.Authorization;

namespace Mercado.Controllers
{
    [Authorize]
    public class ProductController : Controller
    {
        private readonly MercadoDbContext _context;

        public ProductController(MercadoDbContext context)
        {
            _context = context;
        }

        // GET: Produto
        public async Task<IActionResult> Index()
        {
            var produtos = _context.Product.Include(p => p.Fornecedor).ToListAsync();
            return View(await produtos);
        }

        // GET: Produto/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produto = await _context.Product
                .Include(p => p.Fornecedor)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (produto == null)
            {
                return NotFound();
            }

            return View(produto);
        }

        // GET: Produto/Create
        public async Task<IActionResult> Create()
        {
            ViewData["Provider"] = await _context.Provider.ToListAsync();

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Quantity,Price,ProviderId")] Product produto)
        {
            if (ModelState.IsValid)
            {
                _context.Add(produto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Provider"] = new SelectList(_context.Provider, "Id", "Company", produto.ProviderId);
            return View(produto);
        }

        // GET: Produto/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produto = await _context.Product.FindAsync(id);
            if (produto == null)
            {
                return NotFound();
            }
            ViewData["Provider"] = await _context.Provider.ToListAsync();
            return View(produto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Quantity,Price,ProviderId")] Product produto)
        {
            if (id != produto.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(produto);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProdutoExists(produto.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProviderId"] = new SelectList(_context.Provider, "Id", "Id", produto.ProviderId);
            return View(produto);
        }

        // GET: Produto/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produto = await _context.Product
                .Include(p => p.Fornecedor)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (produto == null)
            {
                return NotFound();
            }

            return View(produto);
        }

        // POST: Produto/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var produto = await _context.Product.FindAsync(id);
            _context.Product.Remove(produto);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProdutoExists(int id)
        {
            return _context.Product.Any(e => e.Id == id);
        }
    }
}

Mercado/Views/Shared/_Layout.cshtml
@using Mercado.Data.Identity
@using Microsoft.AspNetCore.Identity
@inject SignInManager<UserCustom> SignInManager
@inject UserManager<UserCustom> UserManager

<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mercado</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <header class="p-3 bg-dark text-white">
        <div class="d-flex flex-wrap align-items-center justify-content-between">
            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0 align-items-center">
                <li>
                    <a class="navbar-brand logo" asp-area="" asp-controller="Home" asp-action="Index">
                        <p>Mercado</p>
                        <img src="~/images/logo.png" />
                    </a>
                </li>
                <li>
                    <a class="nav-link px-2 text-white" asp-area="" asp-controller="Provider"
                        asp-action="Index">Fornecedor</a>
                </li>
                <li>
                    <a class="nav-link px-2 text-white" asp-area="" asp-controller="Product"
                        asp-action="Index">Produtos</a>
                </li>
            </ul>
            <div class="text-end">
                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0 align-items-center">
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-white">Olá @((await UserManager.GetUserAsync(User)).Name)!</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Administration"
                        asp-action="ListRole">Funções</a>
                        </li>

                        <li class="nav-item">
                            <form id="logoutForm" asp-controller="account" asp-action="logout" class="form-inline">
                                <button id="logout" type="submit"
                                class="logout-btn nav-link btn btn-link text-white">
                                Sair
                                <svg xmlns="http://www.w3.org/2000/svg" fill="white" height="24" width="24"><path d="M8.9 10.85H16.95L14.425 8.35L16 6.725L21.275 12L16 17.275L14.425 15.65L16.95 13.15H8.9ZM12.05 2.8V5.075H5Q5 5.075 5 5.075Q5 5.075 5 5.075V18.925Q5 18.925 5 18.925Q5 18.925 5 18.925H12.05V21.2H5Q4.05 21.2 3.388 20.538Q2.725 19.875 2.725 18.925V5.075Q2.725 4.125 3.388 3.462Q4.05 2.8 5 2.8Z"/></svg>
                                </button>
                            </form>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Account"
                            asp-action="Login">
                            Login
                            <svg xmlns="http://www.w3.org/2000/svg" fill="white" height="24" width="24"><path d="M9.825 17.275 8.25 15.65 10.75 13.15H2.725V10.85H10.75L8.25 8.35L9.825 6.725L15.1 12ZM11.95 21.2V18.925H19Q19 18.925 19 18.925Q19 18.925 19 18.925V5.075Q19 5.075 19 5.075Q19 5.075 19 5.075H11.95V2.8H19Q19.95 2.8 20.613 3.462Q21.275 4.125 21.275 5.075V18.925Q21.275 19.875 20.613 20.538Q19.95 21.2 19 21.2Z"/></svg>
                        </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Account"
                            asp-action="Register">
                            Cadastrar
                            <svg xmlns="http://www.w3.org/2000/svg" fill="white" height="24" width="24"><path d="M12.6 11.65Q13.225 10.95 13.538 10.05Q13.85 9.15 13.85 8.2Q13.85 7.225 13.538 6.325Q13.225 5.425 12.6 4.75Q13.925 4.9 14.788 5.887Q15.65 6.875 15.65 8.2Q15.65 9.525 14.788 10.512Q13.925 11.5 12.6 11.65ZM17.85 19.3V16.95Q17.85 16.15 17.513 15.412Q17.175 14.675 16.575 14.15Q17.725 14.525 18.688 15.175Q19.65 15.825 19.65 16.95V19.3ZM19.65 12.75V10.75H17.65V9.25H19.65V7.25H21.15V9.25H23.15V10.75H21.15V12.75ZM8.35 11.7Q6.9 11.7 5.875 10.662Q4.85 9.625 4.85 8.2Q4.85 6.75 5.875 5.725Q6.9 4.7 8.35 4.7Q9.8 4.7 10.825 5.725Q11.85 6.75 11.85 8.2Q11.85 9.625 10.825 10.662Q9.8 11.7 8.35 11.7ZM0.85 19.3V17.075Q0.85 16.35 1.25 15.725Q1.65 15.1 2.3 14.75Q3.8 14.025 5.3 13.662Q6.8 13.3 8.35 13.3Q9.875 13.3 11.387 13.662Q12.9 14.025 14.375 14.75Q15.05 15.1 15.45 15.725Q15.85 16.35 15.85 17.075V19.3ZM8.35 10.2Q9.175 10.2 9.763 9.612Q10.35 9.025 10.35 8.2Q10.35 7.375 9.763 6.787Q9.175 6.2 8.35 6.2Q7.525 6.2 6.938 6.787Q6.35 7.375 6.35 8.2Q6.35 9.025 6.938 9.612Q7.525 10.2 8.35 10.2ZM2.35 17.8H14.35V17.075Q14.35 16.775 14.175 16.525Q14 16.275 13.7 16.1Q12.4 15.475 11.062 15.137Q9.725 14.8 8.35 14.8Q6.975 14.8 5.638 15.137Q4.3 15.475 3 16.1Q2.7 16.275 2.525 16.525Q2.35 16.775 2.35 17.075ZM8.35 8.2Q8.35 8.2 8.35 8.2Q8.35 8.2 8.35 8.2Q8.35 8.2 8.35 8.2Q8.35 8.2 8.35 8.2Q8.35 8.2 8.35 8.2Q8.35 8.2 8.35 8.2Q8.35 8.2 8.35 8.2Q8.35 8.2 8.35 8.2ZM8.35 17.8Q8.35 17.8 8.35 17.8Q8.35 17.8 8.35 17.8Q8.35 17.8 8.35 17.8Q8.35 17.8 8.35 17.8Q8.35 17.8 8.35 17.8Q8.35 17.8 8.35 17.8Q8.35 17.8 8.35 17.8Q8.35 17.8 8.35 17.8Z"/></svg>
                        </a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </header>

    <main>
        @RenderBody()
    </main>

    <footer>
        <div class="container">
            &copy; 2022 - Mercado
        </div>
    </footer>
    <script src="https://kit.fontawesome.com/4024ba868b.js" crossorigin="anonymous"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @*<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>*@
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
        crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>